[package]
name = "tui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
render = { path = "../render" }
unicode-width = { workspace = true }
crossterm = { workspace = true }
taffy = { workspace = true }
syntect = { workspace = true }
once_cell = { workspace = true }
rustc-hash = "2.0"
smallvec = "1.13"
