[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[dependencies]
term = { path = "../term" }
render = { path = "../render" }
unicode-width = "0.2.0"
tokio = { version = "1", features = ["full"] }
rayon = "1.10.0"
