[package]
name = "tui"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
term = { path = "../term" }
render = { path = "../render" }
unicode-width = { workspace = true }
tokio = { workspace = true }
crossterm = { workspace = true }
taffy = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
