[package]
name = "rsille_example"
version = "0.1.0"
edition = "2024"

[dependencies]
rsille = { path = "../" }

[[example]]
name = "basic_canvas"
path = "basic_canvas.rs"

[[example]]
name = "simple"
path = "simple.rs"
