[package]
name = "render"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
term = { path = "../term" }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
rayon = { workspace = true }
unicode-width = { workspace = true }
