[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
term = { path = "../term" }
async-trait = "0.1.84"
futures = "0.3.31"
rayon = "1.10.0"
log = { version = "0.4", features = ["std"], optional = true }
unicode-width = "0.2.0"

[features]
log = ["dep:log"]
